#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd


FEATURE_NAMES = [
    "intercept",
    "coef_sin",
    "coef_cos",
    "coef_sin2",
    "coef_cos2",
    "coef_dist",
    "coef_height",
]


def build_features(df: pd.DataFrame) -> np.ndarray:
    theta = df["rotation_angle"].to_numpy(dtype=float)
    distance = df["horizontal_distance"].to_numpy(dtype=float)
    height = df["height"].to_numpy(dtype=float)
    return np.column_stack(
        [
            np.ones_like(theta),
            np.sin(theta),
            np.cos(theta),
            np.sin(2.0 * theta),
            np.cos(2.0 * theta),
            distance,
            height,
        ]
    )


def fit_axis(features: np.ndarray, target: np.ndarray) -> tuple[np.ndarray, dict]:
    coeffs, _, _, _ = np.linalg.lstsq(features, target, rcond=None)
    pred = features @ coeffs
    residual = target - pred
    metrics = {
        "mae": float(np.mean(np.abs(residual))),
        "rmse": float(np.sqrt(np.mean(residual ** 2))),
        "max_abs": float(np.max(np.abs(residual))),
    }
    return coeffs, metrics


def coeffs_to_dict(coeffs: np.ndarray) -> dict:
    return {name: float(value) for name, value in zip(FEATURE_NAMES, coeffs)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Fit big-buff moving compensation.")
    parser.add_argument("csv", type=Path, help="CSV file generated by BuffShootingTableCalibration")
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    required = {
        "rotation_angle",
        "horizontal_distance",
        "height",
        "relative_yaw",
        "relative_pitch",
    }
    missing = required - set(df.columns)
    if missing:
        raise SystemExit(f"Missing columns: {sorted(missing)}")

    features = build_features(df)
    pitch_coeffs, pitch_metrics = fit_axis(features, df["relative_pitch"].to_numpy(dtype=float))
    yaw_coeffs, yaw_metrics = fit_axis(features, df["relative_yaw"].to_numpy(dtype=float))

    result = {
        "buff_shooting_table_calib": {
            "enable": True,
            "apply_on_big_buff_only": True,
            "pitch": coeffs_to_dict(pitch_coeffs),
            "yaw": coeffs_to_dict(yaw_coeffs),
        }
    }

    print("Pitch metrics:", json.dumps(pitch_metrics, indent=2, ensure_ascii=False))
    print("Yaw metrics:", json.dumps(yaw_metrics, indent=2, ensure_ascii=False))
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
