#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd


FEATURE_NAMES = ["intercept", "coef_z", "coef_d", "coef_z2", "coef_zd", "coef_d2"]


def build_features(df: pd.DataFrame) -> np.ndarray:
    z = df["z_height"].to_numpy(dtype=float)
    d = df["horizontal_distance"].to_numpy(dtype=float)
    return np.column_stack([np.ones_like(z), z, d, z * z, z * d, d * d])


def fit_axis(features: np.ndarray, target: np.ndarray) -> tuple[np.ndarray, dict]:
    coeffs, _, _, _ = np.linalg.lstsq(features, target, rcond=None)
    pred = features @ coeffs
    residual = target - pred
    metrics = {
        "mae": float(np.mean(np.abs(residual))),
        "rmse": float(np.sqrt(np.mean(residual ** 2))),
        "max_abs": float(np.max(np.abs(residual))),
    }
    return coeffs, metrics


def coeffs_to_dict(coeffs: np.ndarray) -> dict:
    return {name: float(value) for name, value in zip(FEATURE_NAMES, coeffs)}


def main() -> None:
    parser = argparse.ArgumentParser(description="Fit static buff shooting-table compensation.")
    parser.add_argument("csv", type=Path, help="CSV file generated by BuffStaticShootingTableCalibration")
    args = parser.parse_args()

    df = pd.read_csv(args.csv)
    required = {"z_height", "horizontal_distance", "relative_yaw", "relative_pitch"}
    missing = required - set(df.columns)
    if missing:
        raise SystemExit(f"Missing columns: {sorted(missing)}")

    features = build_features(df)
    pitch_coeffs, pitch_metrics = fit_axis(features, df["relative_pitch"].to_numpy(dtype=float))
    yaw_coeffs, yaw_metrics = fit_axis(features, df["relative_yaw"].to_numpy(dtype=float))

    result = {
        "shoot_table_adjust": {
            "enable": True,
            "pitch": coeffs_to_dict(pitch_coeffs),
            "yaw": coeffs_to_dict(yaw_coeffs),
        }
    }

    print("Pitch metrics:", json.dumps(pitch_metrics, indent=2, ensure_ascii=False))
    print("Yaw metrics:", json.dumps(yaw_metrics, indent=2, ensure_ascii=False))
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
